### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ToTensor** [flytocc/ODConv2d_pytorch#1]
`line 16, in _init_ padding_mode, device, dtype)
TypeError:__init__() takes from 4 to 10 positional arguments but 12 were given`

**Comment by flytocc** [comment]
Problems caused by pytorch version. The problem has been fixed in the latest code.

**Comment by ToTensor** [comment]
Thank you for your reply, I'll replace ODConv2d YOLOv5 backbone network of convolution, I found my Params and FLOPS was reduced by half, I think this the realization of the convolution is not according to this article at [https://openreview.net/forum?id=DmpCfq6Mg39]. Which article is the basis for the realization of this convolution?

**Comment by ToTensor** [comment]
I am sorry for my negligence. It is this paper that you refer to, but the effect achieved on my YOLO model does not increase, but achieves the effect of lightweight.

**Comment by 18109359681** [comment]
size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 64, 64, 1, 1]).
你好，我在替换resnet50中的卷积之后出现这个问题，可以帮我解答一下嘛

**Comment by flytocc** [comment]
> size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 64, 64, 1, 1]). 你好，我在替换resnet50中的卷积之后出现这个问题，可以帮我解答一下嘛

重开一个issue吧
